# Page settings
baseURL = "https://reverent-snyder-0ea6d4.netlify.com/"
languageCode = "es"
DefaultContentLanguage = "es"
title = "Desarrollador | Alejandro López"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
author = "CowboySmall"
description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"
primaryColor = "#36859a"
textPrimaryColor = "#555"

[params.profile]
enable = true
name = "Alejandro López"
tagline = "Desarrollador de software"
avatar = "profile.png"
[params.contact]
  enable = true
  location = "Santiago de Chile, Chile"

  [[params.contact.list]]
  icon = "fas fa-envelope-square"
  url = "mailto:#"
  text = "alejandrolopez.gd@gmail.com"
  [[params.contact.list]]
  icon = "fas fa-globe"
  url = "https://alejandrolopez.web.app"
  text = "www.alejandrolopez.web.app"
[params.skills]
  enable = true

  [[params.skills.list]]
  title = "Technical"
  [[params.skills.list.items]]
  details = "JavaScript/Angular/React/Vue"
  [[params.skills.list.items]]
  details = "Python/Ruby/PHP"
  [[params.skills.list.items]]
  details = "Node.js/ASP.NET"
  [[params.skills.list.items]]
  details = "PostgreSQL/MySQL"
  [[params.skills.list.items]]
  details = "Object-oriented design"
  [[params.skills.list.items]]
  details = "Design and implement database structures"
  [[params.skills.list.items]]
  details = "Lead and deliver complex software systems"

  [[params.skills.list]]
  title = "Professional"
  [[params.skills.list.items]]
  details = "Effective communication"
  [[params.skills.list.items]]
  details = "Team player"
  [[params.skills.list.items]]
  details = "Strong problem solver"
  [[params.skills.list.items]]
  details = "Good time management"

[params.education]
  enable = true

  [[params.education.list]]
  degree = "Ingeniería en Informática"
  university = "Universidad Privada Dr. Rafael Belloso Chacín"
  dates = "2013 - 2017"
  [[params.education.list]]
  degree = "Diplomado: webmáster"
  university = "Universidad Privada Dr. Rafael Belloso Chacín"
  dates = "2016"

[params.awards]
  enable = true

  [[params.awards.list]]
  name = "Award Lorem Ipsum"
  body = "Microsoft lorem ipsum"
  date = "2019"
  [[params.awards.list]]
  name = "Award Donec Sodales"
  body = "Oracle Aenean"
  date = "2017"

[params.languages]
  enable = true

  [[params.languages.list]]
  name = "Español"
  level = "Nativo"
  [[params.languages.list]]
  name = "English"
  level = "Profesional"
  [[params.languages.list]]
  name = "Francés"
  level = "Básico"

[params.interests]
  enable = true

  [[params.interests.list]]
  name = "Tecnología"
  [[params.interests.list]]
  name = "Ciclismo"
  [[params.interests.list]]
  name = "Idiomas"

[params.summary]
  enable = true
  text = "Egresado de la Universidad Dr. Rafael Belloso Chacín, poseo habilidades que me permiten utilizar el tiempo de manera eficaz, realizar investigaciones y solucionar problemas con agilidad. Me relaciono fácilmente con la tecnología y me desenvuelvo en ella con comodidad, incluso bajo presión."

[params.experience]
  enable = true

  [[params.experience.list]]
  title = "Desarrollador de front-end"
  dates = "Abr 2018 - Present"
  company = "Nectia Software"
  details = "Actualmente realizo labores de maquetación de aplicaciones web y móviles, medición del comportamiento de usuarios a través de herramientas de analítica y feedback para su posterior estudio, así como también participo en A/B testing y desarrollo/implementación de prototipos."
  [[params.experience.list.items]]
  details = "Lorem ipsum dolor sit amet, consectetuer."
  [[params.experience.list.items]]
  details = "Aenean commodo ligula eget dolor."
  [[params.experience.list.items]]
  details = "Etiam ultricies nisi vel augue."

  [[params.experience.list]]
  title = "Desarrollador de front-end"
  dates = "Abr 2017 - Feb 2018"
  company = "Sistemas Ventor"
  details = "Fui responsable del desarrollo de front-end de múltiples aplicaciones cuyo fin es administrar la distribución masiva de productos, bajo ambiente web y móvil (Android)."
  [[params.experience.list.items]]
  details = "Optimicé el tamaño promedio de las aplicaciones en un 60% aplicando técnicas de compresión de archivos."
  [[params.experience.list.items]]
  details = "Simplifiqué el proceso de distribución de nuevas versiones implementando un sistema de actualizaciones OTA"
  [[params.experience.list.items]]
  details = "Automaticé diferentes tareas de desarrollo y despliegue, contribuyendo a un aumento de la productividad"


  [[params.experience.list]]
  title = "Desarrollador de software"
  dates = "Ene 2017 - Abr 2017"
  company = "Megagroup L.A."
  details = "Fui responsable del desarrollo de aplicaciones de gestión documental y sitios web corporativos y gubernamentales, adaptables a sistemas de escritorio y móviles."

  [[params.experience.list]]
  title = "Preparador docente/Tutor"
  dates = "Ene 2016 - Dic 2017"
  company = "Universidad Dr. Rafael B. Chacín"
  details = "Soporte técnico en el área de la informática (software de oficina, programación y diseño gráfico) dirigido tanto a profesores como a estudiantes de la universidad."

[params.projects]
  enable = true

  [[params.projects.list]]
  title = "Project Lorem Ipsum"
  meta = "Open Source"
  tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

  [[params.projects.list]]
  title = "Project Sed Fringilla"
  meta = "Open Source"
  tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

  [[params.projects.list]]
  title = "Project Praesent"
  meta = "Open Source"
  tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
[params.information]
  enable = true

  [[params.information.list]]
  title = "Papers"
  [[params.information.list.items]]
  details = "2018 · Lorem Ipsum"
  [[params.information.list.items]]
  details = "2016 · Sed Fringilla"

[params.social]
  enable = true

  [[params.social.list]]
  icon = "fab fa-gitlab"
  url = "//gitlab.com/arlopezg"
  title = "arlopezg"
  [[params.social.list]]
  icon = "fab fa-linkedin"
  url = "//www.linkedin.com/in/arlopezg/"
  title = "arlopezg"
  [[params.social.list]]
  icon = "fab fa-instagram"
  url = "//www.instagram.com/arlopezg/"
  title = "@arlopezg"
