# Page settings
baseURL = "/"
languageCode = "es"
DefaultContentLanguage = "es"
title = "Contador Público | Alejandro López"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-113183171-1"

[params]
author = "CowboySmall"
description = "Profesional de la contaduría y administración de empresas con experiencia en PYMEs y un fuerte foco en el área administrativa y logística."
primaryColor = "#36859a"
textPrimaryColor = "#555"

[params.profile]
enable = true
name = "Alejandro López"
tagline = "Contador Público y Administrador de Empresas"
avatar = "avatar.png"

  [params.contact]
    enable = true
    location = "Santiago de Chile, Chile"
    [[params.contact.list]]
    icon = "fas fa-envelope-square"
    url = "mailto:alejandro.elb71@gmail.com"
    text = "alejandro.elb71@gmail.com"
    [[params.contact.list]]
    icon = "fas fa-phone"
    url = "tel:56946577360"
    text = "+56 9 4657 7360"

  [params.languages]
    enable = false
  [params.social]
    enable = true
    [[params.social.list]]
    icon = "fab fa-linkedin"
    url = "//www.linkedin.com/in/alejandro-elb/"
    title = "Mi LinkedIn"

[languages]
  [languages.es]
    [languages.es.params.skills]
      enable = true

      [[languages.es.params.skills.list]]
      title = "Técnicas"
      [[languages.es.params.skills.list.items]]
      details = "Excel"
      [[languages.es.params.skills.list.items]]
      details = "Laudus ERP"

      [[languages.es.params.skills.list]]
      title = "Profesionales"
      [[languages.es.params.skills.list.items]]
      details = "Comunicación efectiva"
      [[languages.es.params.skills.list.items]]
      details = "Pensamiento crítico"
      [[languages.es.params.skills.list.items]]
      details = "Trabajo en equipo"

    [languages.es.params.education]
      enable = true

      [[languages.es.params.education.list]]
      degree = "Contaduría Pública"
      university = "Universidad José G. Hernández"
      dates = "2010 - 2014"
      [[languages.es.params.education.list]]
      degree = "Admin. de Empresas"
      university = "Instituto Universitario de Tecnología"
      dates = "1990 - 1993"


    [languages.es.params.interests]
      enable = true

      [[languages.es.params.interests.list]]
      name = "Ciclismo"
      [[languages.es.params.interests.list]]
      name = "Cocina"
      [[languages.es.params.interests.list]]
      name = "Lectura"

    [languages.es.params.summary]
      enable = true
      text = "Profesional de la contabilidad y administración de empresas con experiencia en PYMEs y un fuerte foco en el área administrativa y logística. Me considero una persona creativa que busca aportar valor y me motiva trabajar en equipo."

    [languages.es.params.experience]
      enable = true

      [[languages.es.params.experience.list]]
      title = "Supervisor de Logística"
      dates = "Agosto 2021 - Actualidad"
      company = "IronTrust Ltda."
      companyUrl = "https://irontrust.cl/"
      details = "Empresa dedicada a la importación de materiales para la construcción, como tapas de alcantarilla y estructuras provisionales como andamios. <br/><br/> Estoy a cargo de la supervisión de bodegas y de gestionar la recepción y despacho de diferentes productos, para lo cual me mantengo en contacto con diferentes proveedores y clientes.<br/><br/> Entre mis actividades diarias se encuentran:"

      [[languages.es.params.experience.list.items]]
      details = "Organizar pedidos de venta entrantes"
      [[languages.es.params.experience.list.items]]
      details = "Dirigir equipos de almacén, conformados por obreros y despachadores"
      [[languages.es.params.experience.list.items]]
      details = "Elaborar guías de despacho"
      [[languages.es.params.experience.list.items]]
      details = "Planificar rutas de despacho"
      [[languages.es.params.experience.list.items]]
      details = "Elaborar facturas a clientes y notas de crédito"
      [[languages.es.params.experience.list.items]]
      details = "Manejo de vehiculos"

      [[languages.es.params.experience.list]]
      title = "Jefe de Operaciones"
      dates = "Octubre 2020 - Julio 2021"
      company = "Logística y Transporte Lauquén SpA"
      details = "Empresa de servicio dedicada al transporte de productos que sirve principalmente a Falabella y Correos de Chile.<br/><br/>Entre mis tareas del día a día realicé:"

      [[languages.es.params.experience.list.items]]
      details = "Organizar pedidos de venta entrantes"
      [[languages.es.params.experience.list.items]]
      details = "Supervisión de compras"
      [[languages.es.params.experience.list.items]]
      details = "Cobranzas"
      [[languages.es.params.experience.list.items]]
      details = "Control de facturas"
      [[languages.es.params.experience.list.items]]
      details = "Control de nómina"

      [[languages.es.params.experience.list]]
      title = "Jefe de Tienda"
      dates = "Enero 2020 - Junio 2020"
      company = "Hi-Work Ltda."
      details = ""

      [[languages.es.params.experience.list.items]]
      details = "Pago de proveedores"
      [[languages.es.params.experience.list.items]]
      details = "Manejo de inventarios"
      [[languages.es.params.experience.list.items]]
      details = "Compras"
      [[languages.es.params.experience.list.items]]
      details = "Atención al cliente"
      [[languages.es.params.experience.list.items]]
      details = "Apertura y cierre del local"
      [[languages.es.params.experience.list.items]]
      details = "Reposición de mercancía"

      [[languages.es.params.experience.list]]
      title = "Administrador / Auditor"
      dates = "Octubre 2018 - Julio 2019"
      company = "Sistemas de Propulsión"
      companyUrl = "http://www.sistemasdepropulsion.com"

      [[languages.es.params.experience.list.items]]
      details="Control de planificación financiera"
      [[languages.es.params.experience.list.items]]
      details="Cuentas por cobrar y cuentas por pagar (clientes y proveedores)"
      [[languages.es.params.experience.list.items]]
      details="Control de inventario y activos"
      [[languages.es.params.experience.list.items]]
      details="Manejo y gestión de flota interna de vehículos"
      [[languages.es.params.experience.list.items]]
      details="Revisión y controles administrativos internos"

      [[languages.es.params.experience.list]]
      title = "Jefe de administración"
      dates = "Enero 2009 - Octubre 2018"
      company = "Energías Renovables de Venezuela"
      details = "Empresa dedicada a la importación y mantenimiento de productos relacionados a la energía renovable, tales como paneles solares o motores a gas."

      [[languages.es.params.experience.list.items]]
      details="Manejo administrativo y de operaciones"
      [[languages.es.params.experience.list.items]]
      details="Cuentas por cobrar y cuentas por pagar (clientes y proveedores)"
      [[languages.es.params.experience.list.items]]
      details="Auditorías de departamentos internos: RR.HH, ventas y compras"
      [[languages.es.params.experience.list.items]]
      details="Administración de contratos de servicios com clientes"
      [[languages.es.params.experience.list.items]]
      details="Control de inventario interno y de servicios"
      [[languages.es.params.experience.list.items]]
      details="Gestión de tributos municipales y servicios públicos"

    [languages.es.params.projects]
      enable = false

      [[languages.es.params.projects.list]]
      title = "Supervisor de Logística"
      meta = "Consulting"
      tagline = "Trabajé junto al equipo de MacroMade como contratista freelance para perfeccionar múltiples sitios web de sus clientes, principalmente construidos en Wordpress y Shopify."
      [[languages.es.params.projects.list.items]]
      title = "Advanced Fiberglass Concepts"
      url = "https://test.com"
      description = "piezas de fibra de vidrio para vehículos todo terreno"
