# Page settings
baseURL = "https://alejandrolopez.web.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Developer | Alejandro López"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-113183171-1"

[params]
author = "CowboySmall"
description = "Hi, I'm Alejandro López. I'm a software engineer specialized on front-end development."
primaryColor = "#36859a"
textPrimaryColor = "#555"

[params.profile]
enable = true
name = "Alejandro López"
tagline = ""
avatar = "images/profile.png"

[params.contact]
  enable = true
  location = "Santiago de Chile, Chile"
  [[params.contact.list]]
  name = "fas fa-envelope-square"
  summary = ""
  url = "mailto:alejandrolopez.gd@gmail.com"
  text = "alejandrolopez.gd@gmail.com"
  [[params.contact.list]]
  name = "fas fa-globe"
  summary = ""
  url = "https://alejandrolopez.web.app"
  text = "www.alejandrolopez.web.app"

[params.skills]
  enable = true
  [[params.skills.list]]
  title = "Technical"
  [[params.skills.list.items]]
  details = "HTML/CSS"
  [[params.skills.list.items]]
  details = "Javascript/EcmaScript"
  [[params.skills.list.items]]
  details = "Angular & React"
  [[params.skills.list.items]]
  details = "Git"
  [[params.skills.list.items]]
  details = "Serverless"
  [[params.skills.list.items]]
  details = "CI/CD"
  [[params.skills.list.items]]
  details = "Lead and deliver complex software systems"

  [[params.skills.list]]
  title = "Professional"
  [[params.skills.list.items]]
  details = "Effective communication"
  [[params.skills.list.items]]
  details = "Team player"
  [[params.skills.list.items]]
  details = "Strong problem solver"
  [[params.skills.list.items]]
  details = "Good time management"
  [[params.skills.list.items]]
  details = "Experienced with Agile"

[params.education]
  enable = true
  [[params.education.list]]
  degree = "B.Sc. Computer Science"
  university = "Dr. Rafael B. Chacín University"
  dates = "2013 - 2017"
  [[params.education.list]]
  degree = "Webmaster Certification"
  university = "Dr. Rafael B. Chacín University"
  dates = "2016"

[params.awards]
  enable = false
  [[params.awards.list]]
  name = "Award Lorem Ipsum"
  body = "Microsoft lorem ipsum"
  date = "2019"
  [[params.awards.list]]
  name = "Award Donec Sodales"
  body = "Oracle Aenean"
  date = "2017"

[params.languages]
  enable = true
  [[params.languages.list]]
  name = "Español"
  level = "Nativo"
  [[params.languages.list]]
  name = "English"
  level = "Professional"
  [[params.languages.list]]
  name = "Français"
  level = "Basique"

[params.interests]
  enable = true
  [[params.interests.list]]
  name = "Technology enthusiast"
  [[params.interests.list]]
  name = "Amateur road cyclist"
  [[params.interests.list]]
  name = "Love to learn languages"

[params.summary]
  enable = true
  text = "A graduate of Dr. Rafael B. Chacín University - I have skills that allow me to use time effectively, conduct research and solve problems with agility."
  [params.summary.bulletpoints]
    enable = true
    [[params.summary.bulletpoints.item]]
    content = "I've got a deep understanding of modern front-end concepts, techniques and tooling aimed to deliver a great experience"
    [[params.summary.bulletpoints.item]]
    content = "Soft skilled — I thrive in collaborating with others, sharing knowledge and reaching goals"

[params.experience]
  enable = true
  [[params.experience.list]]
  title = "Front-end Developer"
  dates = "Apr 2018 - Present"
  company = "Nectia Software"
  details = "Currently working on web and mobile applications."
  [[params.experience.list.items]]
  details = "Improved productivity by automating testing/QA tasks using GitLab CI/CD"
  [[params.experience.list.items]]
  details = "Detected technical debt by implementing SonarQube's CodeQuality & Security reports"
  [[params.experience.list.items]]
  details = "Accelerated page load times and improved SEO by implementing Server-Side Rendering"
  [[params.experience.list.items]]
  details = "Rocketed conversion rates by measuring user behavior through analytical tools (e.g.: Google Analytics & Hotjar)"

  [[params.experience.list]]
  title = "Front-end Developer"
  dates = "Apr 2017 - Feb 2018"
  company = "Ventor Systems"
  details = "I was responsible for the front-end development of multiple applications to manage mass product distribution, under web and mobile environments (Android)."
    [[params.experience.list.items]]
    details = "Brought down the average application size by up to 60% through file compression techniques"
    [[params.experience.list.items]]
    details = "Automated many tasks development, integration and deployment tasks, contributing to an uptick in productivity"
    [[params.experience.list.items]]
    details = "Delivered a stable user experience by providing an Over-The-Air update system, which allowed mobile customers to easily upgrade to the latest releases"

  [[params.experience.list]]
  title = "Front-end Developer"
  dates = "Jan 2017 - Apr 2017"
  company = "Megagroup LatAm"
  details = "I was responsible for the development of document management applications, as well as corporate and internal government websites, adaptable to desktop and mobile systems."
    [[params.experience.list.items]]
    details = "Refined multiple Angular projects' codebases by enforcing the style guides provided by the development team"
    [[params.experience.list.items]]
    details = "Standardised the Git approach by introducing GitFlow - a Dutch branching model designed to streamline the workflow"

  [[params.experience.list]]
  title = "Tutor"
  dates = "Jan 2016 - Dic 2017"
  company = "Dr. Rafael B. Chacín University"
  details = "Technical support in the area of computer science (office software, programming, and graphic design) aimed at both teachers and students of the university."

[params.projects]
  enable = true
  [[params.projects.list]]
  title = "Autoplaza"
  license = "Proprietary"
  tagline = "Autoplaza is a platform aimed to help its users find the best-suited vehicle for their needs."
  projectUrl = "https://autoplaza.cl"
  stackUrl = "https://stackshare.io/nectia-software/autoplaza-usados"
  [[params.projects.list]]
  title = "MacroMade (formerly MICA Interactive)"
  license = "Proprietary"
  tagline = "I worked alongside the team of MacroMade as an independent contractor to overhaul many of their clients' websites, mainly built on Wordpress and Shopify."
  projectUrl = "https://www.linkedin.com/company/micainteractive/"
  [[params.projects.list.item]]
  name = "Advanced Fiberglass Concepts"
  summary = "aftermarket, offroad fiberglass automotive parts producers"
  url = "https://www.advfiberglass.com/"
  [[params.projects.list.item]]
  name = "6 Shore Road"
  summary = "versatile and luxury swimwear"
  url = "https://www.6shoreroad.com/"
  [[params.projects.list.item]]
  name = "Wallark"
  summary = "Finnish elegant décor and craftmanship for ceilings and interior design"
  url = "https://www.wallark.com/"
  [[params.projects.list.item]]
  name = "HoneyCat Jewelry"
  summary = "high-quality, meaningful and sensibly-priced jewelry"
  url = "https://www.honeycat-jewelry.com/"
  [[params.projects.list.item]]
  name = "Gramco"
  summary = "funeral and cremmatoria supplies"
  url = "https://www.gramco.com/"
  [[params.projects.list.item]]
  name = "PoolStore Canada"
  summary = "Canadian pool and hot tube supplies"
  url = "https://www.poolstorecanada.ca/"

[params.information]
  enable = false
  [[params.information.list]]
  title = "Papers"
  [[params.information.list.items]]
  details = "2018 · Lorem Ipsum"
  [[params.information.list.items]]
  details = "2016 · Sed Fringilla"

[params.social]
  enable = true
  [[params.social.list]]
  icon = "fab fa-gitlab"
  url = "//gitlab.com/arlopezg"
  title = "@arlopezg"
  [[params.social.list]]
  icon = "fab fa-linkedin"
  url = "//www.linkedin.com/in/arlopezg/"
  title = "@arlopezg"
  [[params.social.list]]
  icon = "fab fa-instagram"
  url = "//www.instagram.com/arlopezg/"
  title = "@arlopezg"
  [[params.social.list]]
  icon = "fab fa-strava"
  url = "//www.strava.com/athletes/33063219"
  title = "@arlopezg"
